import java.util.Random;
import java.util.Scanner;

public class Game {
    // initialize variables
    int score = 0;
    int compScore = 0;
    int roundsWon = 0;
    int roundsLost = 0;

    public int startGame() {
        // create new scanner object
        Scanner scanner = new Scanner(System.in);

        // start game
        System.out.println("Pick rock, paper, or scissors :)\n" +
                "1. Rock\n" +
                "2. Paper\n" +
                "3. Scissors");

        // create a variable to hold the user response using the Scanner object. The response needs to be an integer between 1-3 (1 = Rock, 2 = Paper, 3 = Scissors)
        int response = scanner.nextInt();

        switch (response) {
            case 1:
                System.out.println("You chose: Rock");
                break;
            case 2:
                System.out.println("You chose: Paper");
                break;
            case 3:
                System.out.println("You chose: Scissors");
                break;
            default:
                System.out.println("Invalid response. Please enter 1, 2, or 3");
                startGame();
        }

        // create a variable to hold the cpu response generated by the getCPUResponse() method.
        int cpuResponse = getCPUResponse();
        switch (cpuResponse) {
            case 1:
                System.out.println("The computer chose: Rock");
                break;
            case 2:
                System.out.println("The computer chose: Paper");
                break;
            case 3:
                System.out.println("The computer chose: Scissors");
                break;
        }

        // compare user and cpu response with each other to decide the winner.

        // if user chooses rock
        if (response == 1) {
            Rock rock = new Rock(cpuResponse);
            rock.checkOutcome();

            // if user loses, increase computer's score
            if (rock.checkOutcome() == 0){
                compScore++;
                System.out.println("\nNuggets! The computer won!\n" +
                        "Your score is: " + score + "\n" +
                        "The computer's score is: " + compScore + "\n");

                // if computer reaches three points, they win
                if (compScore == 3){
                    roundsLost++;

                    // reset scores
                    score = 0;
                    compScore = 0;

                    // give user option to start another game
                    System.out.println("\nSorry! The computer won! Would you like to try again?\n" +
                            "1. Yes\n" +
                            "2. No");
                    int choice = scanner.nextInt();
                    switch(choice){
                        case 1:
                            System.out.println("\nOkay, starting another round!\n");
                            System.out.println("*********************");
                            System.out.println("Rounds won: " + roundsWon + "\n" +
                                    "Round lost: " + roundsLost);
                            System.out.println("*********************\n");
                            startGame();
                            break;
                        case 2:
                            System.out.println("\nOkay, see you next time! :)\n");
                            System.out.println("*********************");
                            System.out.println("Rounds won: " + roundsWon + "\n" +
                                    "Round lost: " + roundsLost);
                            System.out.println("*********************\n");
                            System.exit(0);
                            break;
                    }
                }

            // if user wins, increase their score
            } else {
                score++;
                System.out.println("\nGood job! You won!\n" +
                        "Your score is: " + score + "\n" +
                        "The computer's score is: " + compScore + "\n");

                // if user wins three rounds, they win the game
                if(score == 3){
                    roundsWon++;

                    // reset scores
                    score = 0;
                    compScore = 0;

                    // give user option to start another game
                    System.out.println("\nCongrats! You've won! Do you want to play another round?\n" +
                            "1. Yes\n" +
                            "2. No");
                    int choice = scanner.nextInt();
                    switch (choice){
                        case 1:
                            System.out.println("\nOkay, starting another round!\n");
                            System.out.println("*********************");
                            System.out.println("Rounds won: " + roundsWon + "\n" +
                                    "Round lost: " + roundsLost);
                            System.out.println("*********************\n");
                            startGame();
                            break;
                        case 2:
                            System.out.println("\nOkay, see you next time! :)\n");
                            System.out.println("*********************");
                            System.out.println("Rounds won: " + roundsWon + "\n" +
                                    "Round lost: " + roundsLost);
                            System.out.println("*********************\n");
                            System.exit(0);
                            break;
                    }
                }
            }

        // if user chooses paper
        } else if (response == 2) {
            Paper paper = new Paper(cpuResponse);
            paper.checkOutcome();

            // if user loses, increase computer's score
            if (paper.checkOutcome() == 0){
                compScore++;
                System.out.println("\nNuggets! The computer won!\n" +
                        "Your score is: " + score + "\n" +
                        "The computer's score is: " + compScore + "\n");

                // if computer reaches three points, they win the game
                if (compScore == 3){
                    roundsLost++;

                    // reset scores
                    score = 0;
                    compScore = 0;

                    // give user option to start a new game
                    System.out.println("\nSorry! The computer won! Would you like to try again?\n" +
                            "1. Yes\n" +
                            "2. No");
                    int choice = scanner.nextInt();
                    switch(choice){
                        case 1:
                            System.out.println("\nOkay, starting another round!\n");
                            System.out.println("*********************");
                            System.out.println("Rounds won: " + roundsWon + "\n" +
                                    "Round lost: " + roundsLost);
                            System.out.println("*********************\n");
                            startGame();
                            break;
                        case 2:
                            System.out.println("\nOkay, see you next time! :)\n");
                            System.out.println("*********************");
                            System.out.println("Rounds won: " + roundsWon + "\n" +
                                    "Round lost: " + roundsLost);
                            System.out.println("*********************\n");
                            System.exit(0);
                            break;
                    }
                }

            // if user wins, increase their score
            } else {
                score++;
                System.out.println("\nGood job! You won!\n" +
                        "Your score is: " + score + "\n" +
                        "The computer's score is: " + compScore + "\n");

                // if user wins three rounds, they win the game
                if(score == 3){
                    roundsWon++;

                    // reset scores
                    score = 0;
                    compScore = 0;

                    // give user option to start new game
                    System.out.println("\nCongrats! You've won! Do you want to play another round?\n" +
                            "1. Yes\n" +
                            "2. No");
                    int choice = scanner.nextInt();
                    switch (choice){
                        case 1:
                            System.out.println("\nOkay, starting another round!\n");
                            System.out.println("*********************");
                            System.out.println("Rounds won: " + roundsWon + "\n" +
                                    "Round lost: " + roundsLost);
                            System.out.println("*********************\n");
                            startGame();
                            break;
                        case 2:
                            System.out.println("\nOkay, see you next time! :)\n");
                            System.out.println("*********************");
                            System.out.println("Rounds won: " + roundsWon + "\n" +
                                    "Round lost: " + roundsLost);
                            System.out.println("*********************\n");
                            System.exit(0);
                            break;
                    }
                }
            }

        // if user chooses scissors
        } else if (response == 3) {
            Scissors scissors = new Scissors(cpuResponse);
            scissors.checkOutcome();

            // if user loses, increase computer's score
            if (scissors.checkOutcome() == 0){
                compScore++;
                System.out.println("\nNuggets! The computer won!\n" +
                        "Your score is: " + score + "\n" +
                        "The computer's score is: " + compScore + "\n");

                // if computer wins three rounds, they win the game
                if (compScore == 3){
                    roundsLost++;

                    // reset scores
                    score = 0;
                    compScore = 0;

                    // give user option to start a new game
                    System.out.println("\nSorry! The computer won! Would you like to try again?\n" +
                            "1. Yes\n" +
                            "2. No");
                    int choice = scanner.nextInt();
                    switch(choice){
                        case 1:
                            System.out.println("\nOkay, starting another round!\n");
                            System.out.println("*********************");
                            System.out.println("Rounds won: " + roundsWon + "\n" +
                                    "Round lost: " + roundsLost);
                            System.out.println("*********************\n");
                            startGame();
                            break;
                        case 2:
                            System.out.println("\nOkay, see you next time! :)\n");
                            System.out.println("*********************");
                            System.out.println("Rounds won: " + roundsWon + "\n" +
                                    "Round lost: " + roundsLost);
                            System.out.println("*********************\n");
                            System.exit(0);
                            break;
                    }
                }

                // if user wins, increase their score
            } else {
                score++;
                System.out.println("\nGood job! You won!\n" +
                        "Your score is: " + score + "\n" +
                        "The computer's score is: " + compScore + "\n");

                // if user wins three rounds, they win the game
                if(score == 3){
                    roundsWon++;

                    // reset scores
                    score = 0;
                    compScore = 0;

                    // give user option to start new game
                    System.out.println("\nCongrats! You've won! Do you want to play another round?\n" +
                            "1. Yes\n" +
                            "2. No");
                    int choice = scanner.nextInt();
                    switch (choice){
                        case 1:
                            System.out.println("\nOkay, starting another round!\n");
                            System.out.println("*********************");
                            System.out.println("Rounds won: " + roundsWon + "\n" +
                                    "Round lost: " + roundsLost);
                            System.out.println("*********************\n");
                            startGame();
                            break;
                        case 2:
                            System.out.println("\nOkay, see you next time! :)\n");
                            System.out.println("*********************");
                            System.out.println("Rounds won: " + roundsWon + "\n" +
                                    "Round lost: " + roundsLost);
                            System.out.println("*********************\n");
                            System.exit(0);
                            break;
                    }
                }
            }
        }

        startGame();
        return score;
    }

    public int getCPUResponse(){
        // Generate random integers in range 1 to 3
        Random comp = new Random();

        int randomCompNum = comp.nextInt(3) + 1;

        return randomCompNum;
    }
}